version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: foodmarket_postgres
    environment:
      POSTGRES_DB: foodmarket_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - foodmarket_network

volumes:
  postgres_data:

networks:
  foodmarket_network:
